import type { FastifyInstance, FastifyReply } from "fastify";
import { getLlamaBuildCapabilities, getLlamaBuildCapabilitiesForServer } from "../discovery/llama-build-capabilities.js";
import { createConfiguredModelInSnapshot, duplicateConfiguredModelInSnapshot, loadPhase15Domain, mutatePhase15Domain, reconcileBuildFingerprintInSnapshot, updateConfiguredModelInSnapshot, type ConfiguredModelCreateInput } from "../config/phase15-domain.js";
import { synchronizeDiscoveryCatalog } from "../discovery/catalog-sync.js";
import { fingerprintServerExecutable } from "../router/fingerprint.js";
import { isRouterValidationRunning, RouterValidationError, validateFunctionalRouterBuild, type FunctionalRouterValidatorDependencies } from "../router/functional-validator.js";
import { analyzeRouterPreset, buildRouterLaunchPreview, generateRouterPreset, RouterPresetError, type RouterPresetDependencies } from "../router/preset-generator.js";

const bad = (message: string) => ({ error: "invalid_payload", message });
const missing = (message: string) => ({ error: "not_found", message });
const conflict = (message: string) => ({ error: "conflict", message });
const keys = (value: unknown, allowed: string[]): value is Record<string, unknown> => !!value && typeof value === "object" && !Array.isArray(value) && Object.keys(value).every((key) => allowed.includes(key));
const visionArchitectures = new Set(["clip", "llava", "mllama", "qwen2vl", "qwen2.5vl", "internvl", "gemma3", "pixtral"]);
function artifactRoleMismatch(s: Awaited<ReturnType<typeof loadPhase15Domain>>, artifact: Awaited<ReturnType<typeof loadPhase15Domain>>["artifacts"][number]) { const kind = artifact.metadata?.artifactKind; return kind !== undefined && kind !== "unknown" && (kind !== "model" && s.configuredModels.some((model) => model.artifactId === artifact.id) || kind !== "mmproj" && s.configuredModels.some((model) => model.projector?.artifactId === artifact.id)); }
function artifactDto(s: Awaited<ReturnType<typeof loadPhase15Domain>>, artifact: Awaited<ReturnType<typeof loadPhase15Domain>>["artifacts"][number]) { const base = s.configuredModels.filter((model) => model.artifactId === artifact.id); const projector = s.configuredModels.filter((model) => model.projector?.artifactId === artifact.id); const roleMismatch = artifactRoleMismatch(s, artifact); const explicitProjector = base.some((model) => model.projector?.selection === "explicit"); const type = artifact.metadata?.metadata?.["general.type"]; const capability = explicitProjector || visionArchitectures.has((artifact.metadata?.architecture ?? "").toLowerCase()) ? "yes" : typeof type === "string" && ["text", "text-only", "text_only"].includes(type.toLowerCase()) ? "no" : "unknown"; return { ...artifact, configuredModelIds: [...base, ...projector].map((model) => model.id), vision: { capability, module: explicitProjector ? "installed" : capability === "yes" ? "not_found" : capability === "no" ? "not_required" : "unknown" }, role: roleMismatch ? "conflict" : base.length ? "base" : projector.length ? "projector" : "unassigned", selectionStatus: artifact.referenceStatus === "available" && !roleMismatch ? "available" : "invalid" }; }
function modelDto(s: Awaited<ReturnType<typeof loadPhase15Domain>>, model: Awaited<ReturnType<typeof loadPhase15Domain>>["configuredModels"][number]) { const artifact = s.artifacts.find((entry) => entry.id === model.artifactId); const build = s.builds.find((entry) => entry.id === model.buildId); const projectorAssociation = model.projector; const projector = projectorAssociation && s.artifacts.find((entry) => entry.id === projectorAssociation.artifactId); const compatibilityProfileIds = s.compatibilityBindings.filter((binding) => binding.configuredModelId === model.id).map((binding) => binding.legacyProfileId); return { ...model, artifact, build, projector, ...(projectorAssociation ? { projectorAssociation } : {}), validation: { structural: !!artifact && !!build, references: model.referenceStatus, status: model.validationStatus, managedInferenceEligibility: build?.managedInferenceEligibility }, ...(compatibilityProfileIds.length ? { compatibilityProfileIds } : {}) }; }
function buildDto(s: Awaited<ReturnType<typeof loadPhase15Domain>>, build: Awaited<ReturnType<typeof loadPhase15Domain>>["builds"][number]) { return { ...build, validationInProgress: isRouterValidationRunning(build.id), configuredModelIds: s.configuredModels.filter((model) => model.buildId === build.id).map((model) => model.id) }; }

export async function registerPhase15DomainRoutes(app: FastifyInstance, validatorDependencies: FunctionalRouterValidatorDependencies = {}, presetDependencies: RouterPresetDependencies = {}): Promise<void> {
  app.get("/api/model-artifacts", async () => { await synchronizeDiscoveryCatalog(); const s = await loadPhase15Domain(); return { revision: s.revision, artifacts: s.artifacts.map((artifact) => artifactDto(s, artifact)) }; });
  app.get<{ Params: { id: string } }>("/api/model-artifacts/:id", async (request, reply) => { await synchronizeDiscoveryCatalog(); const s = await loadPhase15Domain(); const artifact = s.artifacts.find((entry) => entry.id === request.params.id); return artifact ? { revision: s.revision, artifact: artifactDto(s, artifact) } : reply.status(404).send(missing("Model artifact not found.")); });
  app.patch<{ Params: { id: string }; Body: { kind?: string; metadata?: unknown } }>("/api/model-artifacts/:id", async (request, reply) => { if (!keys(request.body, ["kind", "metadata"])) return reply.status(400).send(bad("Only kind and metadata may be changed.")); try { const result = await mutatePhase15Domain((s) => { const artifact = s.artifacts.find((entry) => entry.id === request.params.id); if (!artifact) throw new Error("NOT_FOUND"); if (request.body.kind !== undefined) { if (!["model", "mmproj", "adapter", "imatrix", "other", "unknown"].includes(request.body.kind)) throw new Error("BAD"); const main = s.configuredModels.some((model) => model.artifactId === artifact.id); const projector = s.configuredModels.some((model) => model.projector?.artifactId === artifact.id); if (main && !["model", "unknown"].includes(request.body.kind) || projector && !["mmproj", "unknown"].includes(request.body.kind)) throw new Error("CONFLICT"); artifact.kind = request.body.kind as typeof artifact.kind; } if (request.body.metadata !== undefined) artifact.metadata = structuredClone(request.body.metadata) as typeof artifact.metadata; return artifact; }); return { revision: result.snapshot.revision, artifact: result.result }; } catch (e) { return e instanceof Error && e.message === "NOT_FOUND" ? reply.status(404).send(missing("Model artifact not found.")) : e instanceof Error && e.message === "CONFLICT" ? reply.status(409).send(conflict("Artifact kind conflicts with dependents.")) : reply.status(400).send(bad("Invalid artifact patch.")); } });
  app.delete<{ Params: { id: string } }>("/api/model-artifacts/:id", async (request, reply) => { try { const result = await mutatePhase15Domain((s) => { const index = s.artifacts.findIndex((entry) => entry.id === request.params.id); if (index < 0) throw new Error("NOT_FOUND"); if (s.configuredModels.some((model) => model.artifactId === request.params.id || model.projector?.artifactId === request.params.id)) throw new Error("CONFLICT"); s.artifacts.splice(index, 1); }); return { revision: result.snapshot.revision, deletedId: request.params.id }; } catch (e) { return e instanceof Error && e.message === "NOT_FOUND" ? reply.status(404).send(missing("Model artifact not found.")) : reply.status(409).send(conflict("Artifact has dependents.")); } });
  app.get("/api/builds", async () => { await synchronizeDiscoveryCatalog(); const s = await loadPhase15Domain(); return { revision: s.revision, builds: s.builds.map((build) => buildDto(s, build)) }; });
  app.get<{ Params: { id: string } }>("/api/builds/:id", async (request, reply) => { await synchronizeDiscoveryCatalog(); const s = await loadPhase15Domain(); const build = s.builds.find((entry) => entry.id === request.params.id); return build ? { revision: s.revision, build: buildDto(s, build) } : reply.status(404).send(missing("Build not found.")); });
  app.get<{ Params: { id: string } }>("/api/builds/:id/capabilities", async (request, reply) => {
    const current = await loadPhase15Domain(); const build = current.builds.find((entry) => entry.id === request.params.id);
    if (!build) return reply.status(404).send(missing("Build not found."));
    if (build.server.owner.scope !== "local") return reply.status(409).send(conflict("Remote Build capability inspection is not supported by this Node."));
    let fingerprint: string; try { fingerprint = await fingerprintServerExecutable(build.server.locator); } catch { return reply.status(409).send(conflict("The resolved llama-server executable is unavailable.")); }
    const manifest = await getLlamaBuildCapabilitiesForServer(build.server.locator, build.id, build.tools);
    if (build.serverFingerprint !== fingerprint || build.staticEvidence?.serverFingerprint !== fingerprint) await mutatePhase15Domain((s) => { const stored = s.builds.find((entry) => entry.id === build.id)!; reconcileBuildFingerprintInSnapshot(s, stored.id, fingerprint); stored.serverFingerprint = fingerprint; stored.staticEvidence = { kind: "static", assessedAt: manifest.inspectedAt, discoveredTools: structuredClone(stored.tools), ...(manifest.versionInfo ? { versionInfo: structuredClone(manifest.versionInfo) } : {}), routerFlags: structuredClone(manifest.router), serverFingerprint: fingerprint, warnings: manifest.warnings.map((warning) => warning.message) }; });
    return manifest;
  });
  app.post<{ Params: { id: string }; Body: { configuredModelId?: string } }>("/api/builds/:id/validate-router", async (request, reply) => {
    if (request.body !== undefined && !keys(request.body, ["configuredModelId"]) || request.body?.configuredModelId !== undefined && typeof request.body.configuredModelId !== "string") return reply.status(400).send(bad("Only configuredModelId may be supplied."));
    try { return await validateFunctionalRouterBuild(request.params.id, request.body?.configuredModelId, validatorDependencies); }
    catch (error) { if (!(error instanceof RouterValidationError)) throw error; if (error.code === "not_found") return reply.status(404).send(missing(error.message)); if (error.code === "invalid_payload") return reply.status(400).send(bad(error.message)); return reply.status(409).send(conflict(error.message)); }
  });
  const presetError = (error: unknown, reply: FastifyReply) => { if (!(error instanceof RouterPresetError)) throw error; if (error.code === "not_found") return reply.status(404).send(missing(error.message)); if (error.code === "invalid_payload") return reply.status(400).send(bad(error.message)); return reply.status(409).send(conflict(error.message)); };
  app.get<{ Params: { id: string } }>("/api/builds/:id/router-preset/preview", async (request, reply) => { try { return (await analyzeRouterPreset(request.params.id, presetDependencies)).preview; } catch (error) { return presetError(error, reply); } });
  app.post<{ Params: { id: string }; Body: unknown }>("/api/builds/:id/router-preset/generate", async (request, reply) => { if (request.body !== undefined && (!keys(request.body, []) || Object.keys(request.body).length > 0)) return reply.status(400).send(bad("Router preset generation does not accept content or path overrides.")); try { return await generateRouterPreset(request.params.id, presetDependencies); } catch (error) { return presetError(error, reply); } });
  app.get<{ Params: { id: string } }>("/api/builds/:id/router-launch/preview", async (request, reply) => { try { return await buildRouterLaunchPreview(request.params.id, presetDependencies); } catch (error) { return presetError(error, reply); } });
  app.patch<{ Params: { id: string }; Body: { classification?: string } }>("/api/builds/:id", async (request, reply) => { if (!keys(request.body, ["classification"]) || request.body.classification !== undefined && !["official", "custom", "experimental", "compatibility", "unknown"].includes(request.body.classification)) return reply.status(400).send(bad("Invalid build patch.")); const result = await mutatePhase15Domain((s) => { const build = s.builds.find((entry) => entry.id === request.params.id); if (!build) throw new Error("NOT_FOUND"); Object.assign(build, request.body); return build; }).catch((e) => e); return result instanceof Error ? reply.status(404).send(missing("Build not found.")) : { revision: result.snapshot.revision, build: result.result }; });
  app.delete<{ Params: { id: string } }>("/api/builds/:id", async (request, reply) => { try { const result = await mutatePhase15Domain((s) => { const index = s.builds.findIndex((entry) => entry.id === request.params.id); if (index < 0) throw new Error("NOT_FOUND"); if (s.configuredModels.some((model) => model.buildId === request.params.id)) throw new Error("CONFLICT"); s.builds.splice(index, 1); }); return { revision: result.snapshot.revision, deletedId: request.params.id }; } catch (e) { return e instanceof Error && e.message === "NOT_FOUND" ? reply.status(404).send(missing("Build not found.")) : reply.status(409).send(conflict("Build has dependents.")); } });
  app.post<{ Body: unknown }>("/api/configured-models/preview", async (request, reply) => {
    if (!keys(request.body, ["draft", "existingId"]) || !keys(request.body.draft, ["displayName", "routerAlias", "artifactId", "buildId", "enabled", "llamaArgs", "flagOverrides", "extraArgs", "projector", "projectorCandidates"]) || request.body.existingId !== undefined && typeof request.body.existingId !== "string") return reply.status(400).send(bad("Invalid configured model preview payload."));
    try {
      const snapshot = structuredClone(await loadPhase15Domain());
      const draft = request.body.draft as ConfiguredModelCreateInput;
      const model = request.body.existingId === undefined ? createConfiguredModelInSnapshot(snapshot, draft) : updateConfiguredModelInSnapshot(snapshot, request.body.existingId, draft as any);
      const dependencies: RouterPresetDependencies = { ...presetDependencies, load: async () => snapshot, mutate: async (mutator) => ({ snapshot, result: await mutator(snapshot) }) };
      const preset = (await analyzeRouterPreset(model.buildId, dependencies)).preview;
      return { preset, launch: await buildRouterLaunchPreview(model.buildId, dependencies) };
    } catch (error) { return error instanceof RouterPresetError ? presetError(error, reply) : error instanceof Error && /not found/.test(error.message) ? reply.status(404).send(missing("Configured model not found.")) : reply.status(/alias|already/.test(error instanceof Error ? error.message : "") ? 409 : 400).send(bad(error instanceof Error ? error.message : "Invalid configured model preview.")); }
  });
  app.get<{ Params: { id: string } }>("/api/configured-models/:id", async (request, reply) => { await synchronizeDiscoveryCatalog(); const s = await loadPhase15Domain(); const model = s.configuredModels.find((entry) => entry.id === request.params.id); return model ? { revision: s.revision, model: modelDto(s, model) } : reply.status(404).send(missing("Configured model not found.")); });
  app.get("/api/configured-models", async () => { await synchronizeDiscoveryCatalog(); const s = await loadPhase15Domain(); return { revision: s.revision, configuredModels: s.configuredModels.map((model) => modelDto(s, model)) }; });
  app.post<{ Body: any }>("/api/configured-models", async (request, reply) => { if (!keys(request.body, ["displayName", "routerAlias", "artifactId", "buildId", "enabled", "llamaArgs", "flagOverrides", "extraArgs", "projector", "projectorCandidates"])) return reply.status(400).send(bad("Invalid configured model payload.")); try { const result = await mutatePhase15Domain((s) => createConfiguredModelInSnapshot(s, request.body as any)); return reply.status(201).send({ revision: result.snapshot.revision, model: result.result }); } catch (e) { return reply.status((e instanceof Error && /alias|already/.test(e.message)) ? 409 : 400).send(bad(e instanceof Error ? e.message : "Invalid configured model.")); } });
  app.patch<{ Params: { id: string }; Body: any }>("/api/configured-models/:id", async (request, reply) => { if (!keys(request.body, ["displayName", "routerAlias", "artifactId", "buildId", "enabled", "llamaArgs", "flagOverrides", "extraArgs", "projector", "projectorCandidates", "warnings"])) return reply.status(400).send(bad("Invalid configured model patch.")); try { const result = await mutatePhase15Domain((s) => updateConfiguredModelInSnapshot(s, request.params.id, request.body as any)); return { revision: result.snapshot.revision, model: result.result }; } catch (e) { return e instanceof Error && /not found/.test(e.message) ? reply.status(404).send(missing("Configured model not found.")) : reply.status(/alias|already/.test(e instanceof Error ? e.message : "") ? 409 : 400).send(bad(e instanceof Error ? e.message : "Invalid configured model patch.")); } });
  app.post<{ Params: { id: string } }>("/api/configured-models/:id/duplicate", async (request, reply) => { try { const result = await mutatePhase15Domain((s) => duplicateConfiguredModelInSnapshot(s, request.params.id)); return reply.status(201).send({ revision: result.snapshot.revision, model: result.result }); } catch (error) { return error instanceof Error && /not found/.test(error.message) ? reply.status(404).send(missing("Configured model not found.")) : reply.status(400).send(bad(error instanceof Error ? error.message : "Configured model cannot be duplicated.")); } });
  app.post<{ Params: { id: string } }>("/api/configured-models/:id/revalidate", async (request, reply) => { try { const result = await mutatePhase15Domain((s) => { const model = s.configuredModels.find((entry) => entry.id === request.params.id); if (!model) throw new Error("configured model not found"); model.validationStatus = "not_validated"; if (model.projector) { const projector = s.artifacts.find((entry) => entry.id === model.projector!.artifactId); model.projector.validationStatus = projector?.referenceStatus === "available" ? "not_validated" : "invalid"; } return updateConfiguredModelInSnapshot(s, model.id, {}); }); return { revision: result.snapshot.revision, model: result.result }; } catch (error) { return error instanceof Error && /not found/.test(error.message) ? reply.status(404).send(missing("Configured model not found.")) : reply.status(400).send(bad(error instanceof Error ? error.message : "Configured model cannot be revalidated.")); } });
  app.delete<{ Params: { id: string } }>("/api/configured-models/:id", async (request, reply) => { try { const result = await mutatePhase15Domain((s) => { const index = s.configuredModels.findIndex((entry) => entry.id === request.params.id); if (index < 0) throw new Error("NOT_FOUND"); if (s.compatibilityBindings.some((binding) => binding.configuredModelId === request.params.id)) throw new Error("BOUND"); s.configuredModels.splice(index, 1); }); return { revision: result.snapshot.revision, deletedId: request.params.id }; } catch (e) { return e instanceof Error && e.message === "NOT_FOUND" ? reply.status(404).send(missing("Configured model not found.")) : reply.status(409).send(conflict("Configured model has a compatibility binding.")); } });
}
