import { expect, test } from "@playwright/test";
const model = { id: "artifact-1", resource: { owner: { scope: "local" }, locator: "C:/models/vision.gguf" }, kind: "model", role: "base", selectionStatus: "available", referenceStatus: "available", configuredModelIds: ["configured-1"], vision: { capability: "yes", module: "installed" }, metadata: { displayName: "vision", status: "ready", warnings: [] } };
const projector = { id: "artifact-mmproj", resource: { owner: { scope: "local" }, locator: "C:/models/mmproj.gguf" }, kind: "mmproj", role: "projector", selectionStatus: "available", referenceStatus: "available", configuredModelIds: [], vision: { capability: "unknown", module: "unknown" } };
test("Models uses authoritative vision and excludes support or role-mismatched artifacts", async ({ page }) => {
  const unknownSupport = { id: "artifact-unknown-mmproj", resource: { owner: { scope: "local" }, locator: "C:/models/unknown-mmproj.gguf" }, kind: "unknown", role: "unassigned", selectionStatus: "available", referenceStatus: "available", configuredModelIds: [], vision: { capability: "unknown", module: "unknown" } };
  const mismatch = { id: "artifact-mismatch", resource: { owner: { scope: "local" }, locator: "C:/models/mismatch.gguf" }, kind: "model", role: "conflict", selectionStatus: "invalid", referenceStatus: "available", configuredModelIds: [], vision: { capability: "unknown", module: "unknown" } };
  const unknown = { id: "artifact-unknown", resource: { owner: { scope: "local" }, locator: "C:/models/unknown.gguf" }, kind: "unknown", role: "unassigned", selectionStatus: "available", referenceStatus: "available", configuredModelIds: [], vision: { capability: "unknown", module: "unknown" } };
  await page.route("**/api/**", (route) => { const path = new URL(route.request().url()).pathname; if (path === "/api/model-artifacts") return route.fulfill({ json: { revision: "1", artifacts: [model, projector, unknownSupport, mismatch, unknown] } }); if (path === "/api/configured-models") return route.fulfill({ json: { revision: "1", configuredModels: [] } }); return route.fulfill({ json: {} }); });
  await page.goto("/#models"); await expect(page.getByText("vision", { exact: true })).toBeVisible(); await expect(page.getByRole("row", { name: /vision.*Yes.*Installed/ })).toBeVisible(); await expect(page.getByRole("row", { name: /unknown.*Unknown.*Unknown/ })).toBeVisible(); await expect(page.getByText("mmproj.gguf")).toHaveCount(0); await expect(page.getByText("mismatch")).toHaveCount(0); await page.getByRole("row", { name: /vision/ }).click(); await expect(page.getByRole("link", { name: "Configure model" })).toBeVisible();
});
