<script lang="ts">
  import type { LlamaCppBuildDetails, RouterLaunchPreview, RouterPresetPreview, RouterRuntimeResponse } from "@obsidianlm/shared";
  import { API_ENDPOINTS, fetchJson } from "../api";
  export let build: LlamaCppBuildDetails;
  export let runtime: RouterRuntimeResponse | null = null;
  export let onChanged: () => void = () => {};
  let message = "", classification = build.classification, preset: RouterPresetPreview | null = null, launch: RouterLaunchPreview | null = null, busy = "";
  $: if (build.classification !== classification && !busy) classification = build.classification;
  $: presetContent = preset?.content ?? "";
  $: boundedPreset = presetContent.length > 32768 ? `${presetContent.slice(0, 32768)}\n\n[Preview truncated at 32 KiB]` : presetContent;
  async function mutate(path: string, method = "POST", body?: unknown, success = "Completed.") { if (busy) return; busy = path; message = ""; try { await fetchJson(path, { method, headers: { "Content-Type": "application/json" }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) }); message = success; await onChanged(); } catch (error) { message = error instanceof Error ? error.message : "Action failed."; } finally { busy = ""; } }
  async function refreshPreviews() { if (busy) return; busy = "preview"; message = ""; try { const [nextPreset, nextLaunch] = await Promise.all([fetchJson<RouterPresetPreview>(API_ENDPOINTS.builds.presetPreview(build.id)), fetchJson<RouterLaunchPreview>(API_ENDPOINTS.builds.launchPreview(build.id))]); preset = nextPreset; launch = nextLaunch; message = "Preview refreshed."; } catch (error) { message = error instanceof Error ? error.message : "Preview unavailable."; } finally { busy = ""; } }
  async function generate() { if (busy) return; busy = "generate"; message = ""; try { preset = await fetchJson<RouterPresetPreview>(API_ENDPOINTS.builds.generatePreset(build.id), { method: "POST" }); message = "Router preset generated."; await onChanged(); } catch (error) { message = error instanceof Error ? error.message : "Preset generation failed."; } finally { busy = ""; } }
  function remove() { if (build.configuredModelIds.length || !confirm(`Delete ${build.displayName}?`)) return; void mutate(API_ENDPOINTS.builds.delete(build.id), "DELETE", undefined, "Build deleted."); }
</script>

<aside class="panel build-inspector" aria-label="Build inspector"><div class="panel-head"><h2 class="section-title">Build inspector</h2><span class="mini-pill">{build.managedInferenceEligibility}</span></div><div class="body">
  <dl><dt>ID</dt><dd>{build.id}</dd><dt>Resource path</dt><dd>{build.resource.locator}</dd><dt>Server path</dt><dd>{build.server.locator}</dd><dt>Version</dt><dd>{build.versionInfo?.raw ?? "Unknown"}</dd><dt>Tools</dt><dd>{build.tools.length ? build.tools.map((tool) => `${tool.kind}: ${tool.path}`).join("; ") : "None"}</dd><dt>Active router</dt><dd>{runtime?.routerState.activeBuildId === build.id ? "Yes" : "No"}</dd></dl>
  <section><h3>Edit details</h3><label>Classification<select bind:value={classification}>{#each ["official", "custom", "experimental", "compatibility", "unknown"] as value}<option>{value}</option>{/each}</select></label><button class="btn" type="button" disabled={!!busy} on:click={() => mutate(API_ENDPOINTS.builds.update(build.id), "PATCH", { classification }, "Build details saved.")}>Save details</button></section>
  <section><h3>Static capability evidence</h3>{#if build.staticEvidence}<p>Assessed {new Date(build.staticEvidence.assessedAt).toLocaleString()} · {build.staticEvidence.routerFlags.status}</p>{#each build.staticEvidence.warnings as warning}<p class="warning">{warning}</p>{/each}{:else}<p>Not inspected.</p>{/if}<button class="btn" type="button" disabled={!!busy} on:click={() => mutate(API_ENDPOINTS.builds.capabilities(build.id), "GET", undefined, "Capabilities inspected.")}>Inspect capabilities</button></section>
  <section><h3>Functional evidence</h3>{#if build.functionalEvidence}<p>State: {build.functionalEvidence.state}</p><ul><li>Launch: {build.functionalEvidence.launchAttempted ? "passed" : "not passed"}</li><li>Preset: {build.functionalEvidence.presetAccepted ? "passed" : "not passed"}</li><li>Health: {build.functionalEvidence.healthVerified ? "passed" : "not passed"}</li><li>Models: {build.functionalEvidence.modelsVerified ? "passed" : "not passed"}</li><li>Catalog boundary: {build.functionalEvidence.catalogBoundaryVerified ? "passed" : "not passed"}</li><li>Required behavior: {build.functionalEvidence.requiredBehaviorVerified ? "passed" : "not passed"}</li></ul>{#each build.functionalEvidence.warnings as warning}<p class="warning">{warning}</p>{/each}{#each build.functionalEvidence.failures as failure}<p class="error">{failure}</p>{/each}{:else}<p>Not run.</p>{/if}<button class="btn primary" type="button" disabled={!!busy || build.validationInProgress} on:click={() => mutate(API_ENDPOINTS.builds.validateRouter(build.id), "POST", undefined, "Router validation requested.")}>{build.validationInProgress || busy === API_ENDPOINTS.builds.validateRouter(build.id) ? "Validating…" : "Validate router"}</button></section>
  <section><h3>Configured Models</h3>{#if build.configuredModelIds.length}{#each build.configuredModelIds as id}<a href={`#/profiles?configuredModel=${id}`}>{id}</a>{/each}{:else}<p>None.</p>{/if}</section>
  <section><h3>Router preset preview</h3><button class="btn" type="button" disabled={!!busy} on:click={refreshPreviews}>{busy === "preview" ? "Refreshing…" : "Refresh previews"}</button><button class="btn primary" type="button" disabled={!!busy} on:click={generate}>{busy === "generate" ? "Generating…" : "Generate preset"}</button>{#if preset}<dl><dt>Freshness</dt><dd>{preset.artifact.freshness}</dd><dt>Validation</dt><dd>{preset.artifact.validationState}</dd><dt>Configured models</dt><dd>{preset.configuredModelIds.length}</dd><dt>Source revision</dt><dd>{preset.artifact.sourceRevision}</dd></dl>{#each preset.artifact.warnings as warning}<p class="warning">{warning}</p>{/each}{#each preset.artifact.errors as error}<p class="error">{error}</p>{/each}<pre>{boundedPreset}</pre>{/if}</section>
  <section><h3>Launch preview</h3>{#if launch}<p>{launch.policy.modelsMax} model maximum · autoload {launch.policy.modelsAutoload ? "enabled" : "disabled"}</p><pre>{launch.command.displayCommand}</pre>{:else}<p>Refresh previews to inspect the launch command.</p>{/if}</section>
  <button class="btn danger" type="button" disabled={!!busy || build.configuredModelIds.length > 0} on:click={remove}>Delete build</button>{#if build.configuredModelIds.length}<small class="warning">Delete is disabled while configured models depend on this Build.</small>{/if}<p role="status">{message}</p>
</div></aside>

<style>
  .body{display:grid;gap:.7rem;padding:1rem;min-width:0}.body label{display:grid;gap:.25rem}.body section{display:grid;gap:.5rem;padding-top:.65rem;border-top:1px solid var(--color-line)}.body section h3,.body section p{margin:0}.body pre{width:100%;max-height:12rem;overflow:auto;white-space:pre-wrap;overflow-wrap:anywhere;background:rgba(3,8,16,.65);padding:.65rem;box-sizing:border-box}.body dl{display:grid;grid-template-columns:7rem minmax(0,1fr);gap:.35rem .5rem;margin:0}.body dt{color:var(--color-muted)}.body dd{margin:0;overflow-wrap:anywhere}.body ul{margin:.1rem 0;padding-left:1.2rem}.warning{color:var(--color-warning)}.error{color:var(--color-danger)}@media(max-width:320px){.build-inspector{min-width:0}.body{padding:.75rem}.body dl{grid-template-columns:1fr}}
</style>
