<script lang="ts">
  import { onMount } from "svelte";
  import type { LlamaBuildCapabilitiesManifest, LlamaCppBuildClassification, LlamaCppBuildDetails, LlamaCppBuildListResponse, RouterLaunchPreview, RouterPresetPreview, RouterRuntimeResponse } from "@obsidianlm/shared";
  import PageHeader from "../components/PageHeader.svelte";
  import { API_ENDPOINTS, fetchJson } from "../api";

  type RouterValidationResponse = { outcome: string; build: LlamaCppBuildDetails };
  let builds: LlamaCppBuildDetails[] = [], runtime: RouterRuntimeResponse | null = null, selected = "", query = "", message = "", classification: LlamaCppBuildClassification = "unknown", classifiedBuildId = "", saving = false, inspecting = false, validating = false, previewing = false, generating = false;
  let capabilities: LlamaBuildCapabilitiesManifest | null = null, preset: RouterPresetPreview | null = null, launch: RouterLaunchPreview | null = null;
  const folderName = (path: string) => path.replace(/[\\/]+$/, "").split(/[\\/]/).pop() || path;
  const ready = (build: LlamaCppBuildDetails) => build.tools.some((tool) => tool.kind === "server" && tool.exists);
  $: rows = builds.filter((build) => `${folderName(build.resource.locator)} ${build.resource.locator} ${build.versionInfo?.raw ?? ""}`.toLowerCase().includes(query.toLowerCase()));
  $: build = builds.find((entry) => entry.id === selected) ?? null;
  $: if (build?.id !== classifiedBuildId) { classifiedBuildId = build?.id ?? ""; classification = build?.classification ?? "unknown"; }
  function selectBuild(id: string) { selected = id; capabilities = null; preset = null; launch = null; message = ""; }
  async function load() { try { const [response, state] = await Promise.allSettled([fetchJson<LlamaCppBuildListResponse>(API_ENDPOINTS.builds.list), fetchJson<RouterRuntimeResponse>(API_ENDPOINTS.runtime.state)]); if (response.status === "fulfilled") builds = response.value.builds; else throw response.reason; runtime = state.status === "fulfilled" ? state.value : null; message = ""; } catch (error) { message = error instanceof Error ? error.message : "Could not load builds."; } }
  async function saveClassification() { if (!build || saving) return; saving = true; message = ""; try { await fetchJson(API_ENDPOINTS.builds.update(build.id), { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ classification }) }); builds = builds.map((entry) => entry.id === build.id ? { ...entry, classification } : entry); message = "Classification saved."; } catch (error) { message = error instanceof Error ? error.message : "Classification could not be saved."; } finally { saving = false; } }
  async function inspectCapabilities() { if (!build || inspecting) return; inspecting = true; message = ""; try { capabilities = await fetchJson<LlamaBuildCapabilitiesManifest>(API_ENDPOINTS.builds.capabilities(build.id)); message = "Static capabilities inspected."; } catch (error) { message = error instanceof Error ? error.message : "Capabilities could not be inspected."; } finally { inspecting = false; } }
  async function validateRouter() { if (!build || validating) return; validating = true; message = ""; try { const result = await fetchJson<RouterValidationResponse>(API_ENDPOINTS.builds.validateRouter(build.id), { method: "POST" }); builds = builds.map((entry) => entry.id === build.id ? result.build : entry); message = `Router validation ${result.outcome}.`; } catch (error) { message = error instanceof Error ? error.message : "Router validation could not run."; } finally { validating = false; } }
  async function previewRouter() { if (!build || previewing) return; previewing = true; message = ""; try { [preset, launch] = await Promise.all([fetchJson<RouterPresetPreview>(API_ENDPOINTS.builds.presetPreview(build.id)), fetchJson<RouterLaunchPreview>(API_ENDPOINTS.builds.launchPreview(build.id))]); message = "Router preset and launch preview ready."; } catch (error) { message = error instanceof Error ? error.message : "Router preview could not be created."; } finally { previewing = false; } }
  async function generatePreset() { if (!build || generating) return; generating = true; message = ""; try { preset = await fetchJson<RouterPresetPreview>(API_ENDPOINTS.builds.generatePreset(build.id), { method: "POST" }); message = "Router preset generated."; } catch (error) { message = error instanceof Error ? error.message : "Router preset could not be generated."; } finally { generating = false; } }
  onMount(() => void load());
</script>

<main class="page-surface builds-page" aria-label="Builds"><PageHeader title="Builds" subtitle="Auto-synced llama.cpp builds." />
  <div class="actions"><label>Search <input bind:value={query} placeholder="Folder, path, or version" /></label><button class="btn" type="button" on:click={() => void load()}>Refresh</button><span role="status">{message}</span></div>
  <div class="layout"><section class="panel list" aria-label="Build library"><div class="table" role="table"><div class="head" role="row"><span>Folder</span><span>Status</span><span>Version</span><span>Active</span></div>{#each rows as item}<button class:active={selected === item.id} class:missing={!ready(item)} class="row" type="button" role="row" on:click={() => selectBuild(item.id)}><strong>{folderName(item.resource.locator)}</strong><span>{ready(item) ? "Ready" : "llama-server.exe not found (possibly broken build)"}</span><span>{item.versionInfo?.raw ?? "Unknown"}</span><span>{runtime?.routerState.activeBuildId === item.id ? "Yes" : "No"}</span></button>{:else}<p class="empty-state">No builds match this search.</p>{/each}</div></section><aside class="panel inspector">{#if build}<h2 class:missing-text={!ready(build)} class="section-title">{folderName(build.resource.locator)}</h2><dl><dt>Readiness</dt><dd class:missing-text={!ready(build)}>{ready(build) ? "Ready" : "Needs attention"}</dd><dt>Validation</dt><dd>{build.validationInProgress ? "Validating" : build.managedInferenceEligibility}</dd><dt>Models</dt><dd>{build.configuredModelIds.length}</dd></dl>
    <section class="inspection" aria-label="Build dependencies and validation"><h3>Dependencies and validation</h3><p>{build.configuredModelIds.length ? build.configuredModelIds.join(", ") : "No configured models depend on this Build."}</p><div class="button-row"><button class="btn" type="button" disabled={inspecting || !ready(build)} on:click={inspectCapabilities}>{inspecting ? "Inspecting…" : "Inspect static capabilities"}</button><button class="btn" type="button" disabled={validating || !ready(build) || build.validationInProgress} on:click={validateRouter}>{validating || build.validationInProgress ? "Validating…" : "Run router validation"}</button></div>{#if capabilities}<p>Router support: {capabilities.router.status}. {capabilities.router.missingRequiredFlags.length ? `Missing: ${capabilities.router.missingRequiredFlags.join(", ")}` : "Required router flags detected."}</p>{/if}{#if build.functionalEvidence?.reason}<p class="missing-text">{build.functionalEvidence.reason}</p>{/if}</section>
    <section class="inspection" aria-label="Router preset and launch"><h3>Router preset</h3><div class="button-row"><button class="btn" type="button" disabled={previewing || !ready(build)} on:click={previewRouter}>{previewing ? "Preparing…" : "Preview router preset"}</button><button class="btn" type="button" disabled={generating || !preset} on:click={generatePreset}>{generating ? "Generating…" : "Generate router preset"}</button></div>{#if preset}<p>Artifact: {preset.artifact.resource.locator} ({preset.artifact.freshness})</p><pre>{preset.content}</pre>{/if}{#if launch}<h3>Launch command preview</h3><pre>{launch.command.displayCommand}</pre>{/if}</section>
    <section class="classification"><label>Classification<select bind:value={classification}>{#each ["official", "custom", "experimental", "compatibility", "unknown"] as value}<option>{value}</option>{/each}</select></label><button class="btn" type="button" disabled={saving} on:click={saveClassification}>{saving ? "Saving…" : "Save classification"}</button></section>{#if !ready(build)}<p class="missing-text">The configured Build resource is missing. Existing profiles were retained.</p>{/if}{:else}<p class="empty-state">Select a Build to inspect.</p>{/if}</aside></div>
</main>

<style>.actions{display:flex;flex-wrap:wrap;gap:.5rem;align-items:end;margin-bottom:.75rem}.actions label{display:grid;gap:.2rem;font-size:.82rem}.actions span{color:var(--color-muted)}.layout{display:grid;grid-template-columns:minmax(0,1fr) minmax(17rem,27rem);gap:1rem}.list{overflow:auto}.table{min-width:40rem}.head,.row{display:grid;grid-template-columns:1.4fr 1fr 1.4fr .5fr;gap:.6rem;align-items:center;padding:.65rem .75rem}.head{font-size:.75rem;color:var(--color-muted);border-bottom:1px solid var(--color-line)}.row{width:100%;text-align:left;color:inherit;background:transparent;border:0;border-bottom:1px solid var(--color-line)}.row:hover,.row.active{background:var(--color-panel-strong)}.missing,.missing-text{color:var(--color-red)}.inspector{padding:1rem}.inspection,.classification{display:grid;gap:.5rem;margin-top:1rem;padding-top:1rem;border-top:1px solid var(--color-line)}.inspection h3{margin:0;font-size:.9rem}.inspection p{margin:0;overflow-wrap:anywhere}.button-row{display:flex;flex-wrap:wrap;gap:.5rem}.classification label{display:grid;gap:.25rem}dl{display:grid;grid-template-columns:6rem minmax(0,1fr);gap:.4rem .6rem}dt{color:var(--color-muted)}dd{margin:0;overflow-wrap:anywhere}pre{max-height:12rem;overflow:auto;margin:0;padding:.5rem;background:var(--color-panel-strong);white-space:pre-wrap;overflow-wrap:anywhere;font:inherit}@media(max-width:760px){.layout{grid-template-columns:1fr}.builds-page{min-width:0;overflow-x:hidden}.table{min-width:34rem}}</style>
