<script lang="ts">
  import { onMount } from "svelte";
  import type { RuntimeLogEntry, RuntimeLogsStreamEvent } from "@obsidianlm/shared";
  import PageHeader from "../components/PageHeader.svelte"; import Panel from "../components/Panel.svelte"; import StatusBadge from "../components/StatusBadge.svelte"; import CopyButton from "../components/CopyButton.svelte";
  import { API_ENDPOINTS, fetchJson, readStoredAdminToken, type JobListResponse, type JobLogsResponse, type RuntimeLogsResponse, type ServiceLogsResponse } from "../api";
  type Entry = RuntimeLogEntry & { key: string };
  let source: "runtime" | "jobs" | "service" = "runtime", entries: Entry[] = [], query = "", streamSource: "all" | RuntimeLogEntry["source"] = "all", severity: "all" | "error" | "warning" = "all", paused = false, state: "connecting" | "live" | "paused" | "reconnecting" | "offline" = "connecting", message = "", controller: AbortController | undefined, reconnect: number | undefined, jobTimer: number | undefined, attempts = 0, selectedJob = "", jobs: JobListResponse["jobs"] = [], destroyed = false;
  let tone: "green" | "amber" | "red" | "muted" = "amber";
  const key = (entry: RuntimeLogEntry) => `${entry.id}:${entry.sequence}:${entry.timestamp}:${entry.source}`;
  $: shown = entries.filter((entry) => entry.message.toLowerCase().includes(query.toLowerCase()) && (streamSource === "all" || entry.source === streamSource) && (severity === "all" || new RegExp(severity === "error" ? "error|fail|fatal" : "warn|warning", "i").test(entry.message)));
  $: tone = state === "live" ? "green" : state === "offline" ? "red" : state === "paused" ? "muted" : "amber";
  function add(entry: RuntimeLogEntry) { const id = key(entry); if (!paused && !entries.some((item) => item.key === id)) entries = [...entries, { ...entry, key: id }].slice(-1000); }
  function clearTimers() { if (reconnect) clearTimeout(reconnect); if (jobTimer) clearTimeout(jobTimer); reconnect = jobTimer = undefined; }
  function stopStream() { controller?.abort(); controller = undefined; if (reconnect) clearTimeout(reconnect); reconnect = undefined; }
  async function loadRuntimeHistory() { try { const data = await fetchJson<RuntimeLogsResponse>(API_ENDPOINTS.runtime.logs(1000)); data.logs.forEach(add); } catch (error) { message = error instanceof Error ? error.message : "Runtime history unavailable"; } }
  async function stream() { stopStream(); if (destroyed || paused || source !== "runtime") return; state = "connecting"; const streamController = new AbortController(); controller = streamController; try { const token = readStoredAdminToken(), response = await fetch(API_ENDPOINTS.runtime.logStream(100), { headers: token ? { Authorization: `Bearer ${token}` } : {}, signal: streamController.signal }); if (!response.ok || !response.body) throw new Error(`Stream unavailable (${response.status})`); state = "live"; attempts = 0; const reader = response.body.getReader(), decoder = new TextDecoder(); let buffer = ""; while (!destroyed && !paused && source === "runtime") { const next = await reader.read(); if (next.done) throw new Error("Stream closed"); buffer += decoder.decode(next.value, { stream: true }); const blocks = buffer.split(/\r?\n\r?\n/); buffer = blocks.pop() ?? ""; for (const block of blocks) { const event = block.match(/^event:\s*(.+)$/m)?.[1]?.trim(), data = block.split(/\r?\n/).filter((line) => line.startsWith("data:")).map((line) => line.slice(5).trim()).join("\n"); if (!data) continue; try { const parsed = JSON.parse(data) as RuntimeLogEntry | RuntimeLogsStreamEvent; if (event === "log" && "message" in parsed) add(parsed); else if ("event" in parsed && parsed.event === "log") add(parsed.data); } catch { /* malformed SSE payload is ignored */ } } } } catch (error) { if (destroyed || streamController.signal.aborted || paused || source !== "runtime") return; state = "reconnecting"; message = error instanceof Error ? error.message : "Log stream disconnected"; const delay = Math.min(30000, 1000 * 2 ** Math.min(attempts++, 5)); reconnect = window.setTimeout(() => void stream(), delay); } }
  async function loadJobs() { try { jobs = (await fetchJson<JobListResponse>(API_ENDPOINTS.jobs.list)).jobs; if (selectedJob) { const data = await fetchJson<JobLogsResponse>(API_ENDPOINTS.jobs.logs(selectedJob, 1000)); entries = data.logs.map((message, index) => ({ id: index, sequence: index, timestamp: "", source: "system" as const, stream: "system" as const, origin: "unknown" as const, message, key: `${selectedJob}:${index}:${message}` })).slice(-1000); } state = "live"; } catch (error) { state = "offline"; message = error instanceof Error ? error.message : "Could not load job logs"; } }
  async function loadService() { try { const data = await fetchJson<ServiceLogsResponse>(API_ENDPOINTS.logs.service); entries = data.logs.flatMap((file) => file.lines.map((message, index) => ({ id: index, sequence: index, timestamp: file.modifiedAt, source: "system" as const, stream: "system" as const, origin: "unknown" as const, message: `[${file.name}] ${message}`, key: `${file.name}:${index}:${message}` }))).slice(-1000); message = data.warnings.join(" "); state = "live"; } catch (error) { state = "offline"; message = error instanceof Error ? error.message : "Could not load service logs"; } }
  function scheduleJob() { if (jobTimer) clearTimeout(jobTimer); const job = jobs.find((item) => item.id === selectedJob); if (source === "jobs" && job && (job.status === "queued" || job.status === "running")) jobTimer = window.setTimeout(() => { void loadJobs().then(scheduleJob); }, 2000); }
  async function refresh() { clearTimers(); if (source === "runtime") { await loadRuntimeHistory(); void stream(); } else if (source === "jobs") { await loadJobs(); scheduleJob(); } else await loadService(); }
  function setSource(value: typeof source) { stopStream(); clearTimers(); source = value; entries = []; selectedJob = ""; void refresh(); }
  function togglePause() { paused = !paused; if (paused) { stopStream(); clearTimers(); state = "paused"; } else void refresh(); }
  onMount(() => { destroyed = false; const handoff = new URLSearchParams(window.location.hash.split("?")[1] ?? "").get("job"); if (handoff) { source = "jobs"; selectedJob = handoff; } void refresh(); return () => { destroyed = true; stopStream(); clearTimers(); }; });
</script>
<main class="page-surface logs-page" aria-label="Logs"><PageHeader title="Logs" subtitle="Bounded live runtime logs and authenticated service diagnostics." /><div class="actions"><div class="tabs" role="tablist">{#each [["runtime", "Runtime"], ["jobs", "Jobs"], ["service", "Service"]] as item}<button class:active={source === item[0]} on:click={() => setSource(item[0] as typeof source)} type="button">{item[1]}</button>{/each}</div><StatusBadge label={state} tone={tone} /><button class="btn" on:click={togglePause} type="button">{paused ? "Resume" : "Pause"}</button><button class="btn" on:click={() => void refresh()} type="button">Refresh</button><CopyButton value={shown.map((entry) => `${entry.timestamp} ${entry.source} ${entry.message}`).join("\n")} label="Copy" /></div>{#if source === "jobs"}<label class="job-select">Job<select bind:value={selectedJob} on:change={() => void refresh()}><option value="">Select a job</option>{#each jobs as job}<option value={job.id}>{job.type} · {job.status} · {new Date(job.createdAt).toLocaleString()}</option>{/each}</select></label>{/if}<Panel title={`${source} output`}><div class="filters"><label>Search logs<input bind:value={query} placeholder="Filter visible entries" /></label>{#if source === "runtime"}<label>Source<select bind:value={streamSource}><option value="all">All sources</option><option value="stdout">stdout</option><option value="stderr">stderr</option><option value="system">system</option></select></label><label>Severity<select bind:value={severity}><option value="all">All severities</option><option value="warning">Warnings</option><option value="error">Errors</option></select></label>{/if}<button class="btn" on:click={() => entries = []} type="button">Clear visible (client-only)</button><span role="status" aria-live="polite">{message}</span></div><div class="terminal" aria-live="polite">{#each shown as entry}<div><time>{entry.timestamp ? new Date(entry.timestamp).toLocaleTimeString() : ""}</time><b>{entry.source}</b><code>{entry.message}</code></div>{:else}<p>{source === "service" ? "No service logs are available yet." : "No log entries match this view."}</p>{/each}</div></Panel></main>
<style>.actions,.tabs,.filters{display:flex;align-items:center;gap:.6rem;flex-wrap:wrap;margin-bottom:.75rem}.tabs button{background:transparent;border:0;border-bottom:2px solid transparent;padding:.5rem;color:var(--color-muted)}.tabs button.active{color:var(--color-text);border-color:var(--color-purple)}.job-select,.filters label{display:grid;gap:.25rem;color:var(--color-muted);font-size:.8rem;margin-bottom:.75rem}.filters{padding:1rem;margin:0}.filters span{font-size:.8rem;color:var(--color-muted)}.terminal{height:min(65vh,42rem);overflow:auto;padding:.75rem;background:#070d17;font:12px/1.5 ui-monospace,monospace}.terminal div{display:grid;grid-template-columns:5.5rem 4rem minmax(0,1fr);gap:.6rem;padding:.1rem 0}.terminal time,.terminal b{color:var(--color-dim);font-weight:600}.terminal code{overflow-wrap:anywhere;white-space:pre-wrap;color:#cbd6e7}@media(max-width:500px){.terminal{height:55vh}.terminal div{grid-template-columns:1fr}.terminal time,.terminal b{display:none}}</style>
