<script lang="ts">
  import { onMount } from "svelte";
  import PageHeader from "../components/PageHeader.svelte"; import Panel from "../components/Panel.svelte"; import MetricBar from "../components/MetricBar.svelte"; import StatusBadge from "../components/StatusBadge.svelte";
  import { API_ENDPOINTS, fetchJson, type GpuMonitoringStatus, type PortStatus, type ProcessListResponse, type RuntimeState, type StatusResponse } from "../api";
  import { applicationStatus } from "../app-status";
  import { createCompletionAwarePoller, type CompletionAwarePoller } from "../polling";
  type RuntimeResponse = { state: RuntimeState; warnings: string[] };
  let paused = false, message = "", runtime: RuntimeState | null = null, port: PortStatus | null = null, gpu: GpuMonitoringStatus | null = null, processes: ProcessListResponse | null = null, status: StatusResponse | null = null, poller: CompletionAwarePoller | undefined, timer: number | undefined, loading = false;
  const value = (number: number | null) => number === null ? "—" : String(number);
  $: status = $applicationStatus.status;
  async function load() { if (paused || loading) return; loading = true; try { const [runtimeData, portData, gpuData, processData] = await Promise.all([fetchJson<RuntimeResponse>(API_ENDPOINTS.runtime.state), fetchJson<PortStatus>(API_ENDPOINTS.monitoring.ports()), fetchJson<GpuMonitoringStatus>(API_ENDPOINTS.monitoring.gpu), fetchJson<ProcessListResponse>(API_ENDPOINTS.processes.llama)]); runtime = runtimeData.state; port = portData; gpu = gpuData; processes = processData; message = ""; } catch (error) { message = error instanceof Error ? error.message : "Telemetry unavailable"; } finally { loading = false; } }
  function managed(pid: number) { return runtime?.pid === pid ? "Managed" : "External"; }
  onMount(() => { poller = createCompletionAwarePoller(load, 4000); poller.start(); return () => poller?.stop(); });
</script>
<main class="page-surface telemetry-page" aria-label="Telemetry"><PageHeader title="Telemetry" subtitle="Read-only snapshots from runtime, process, port, and GPU monitors." /><div class="actions"><StatusBadge label={paused ? "Paused" : "Polling every 4 seconds"} tone={paused ? "muted" : "green"} /><button class="btn" on:click={() => { paused = !paused; if (paused && timer) clearTimeout(timer); if (!paused) void load(); }} type="button">{paused ? "Resume" : "Pause"}</button><button class="btn" on:click={() => void load()} type="button">Refresh</button><span role="status" aria-live="polite">{message}</span></div><div class="grid"><Panel title="Runtime and managed port"><div class="body"><p><b>Service:</b> {status ? "available" : "unknown"}</p><p><b>Runtime:</b> {runtime?.status ?? "unknown"} · PID {runtime?.pid ?? "—"}</p><p><b>Port:</b> {port?.port.port ?? "—"} · {port?.port.inUse ? "occupied" : "available"} · owner {port?.port.ownerPid ?? "—"}</p><p><b>Detection:</b> {port?.port.detectionMethod ?? "—"}</p><p><b>Conflict:</b> {port?.conflict ? port.conflictMessage ?? "yes" : "no"}</p>{#each port?.port.warnings ?? [] as warning}<small>{warning}</small>{/each}</div></Panel><Panel title="GPU summary"><div class="body"><p>{gpu?.available ? `${gpu.summary.gpuCount} GPU(s) · ${value(gpu.summary.usedMemoryMiB)}/${value(gpu.summary.totalMemoryMiB)} MiB VRAM` : "GPU monitoring unavailable"}</p><p>Driver {gpu?.driverVersion ?? "—"} · CUDA {gpu?.cudaVersion ?? "—"}</p>{#each gpu?.gpus ?? [] as device}<div class="device"><b>{device.name}</b><span>VRAM {value(device.memoryUsedMiB)}/{value(device.memoryTotalMiB)} MiB · GPU {value(device.utilizationGpuPercent)}% · {value(device.temperatureGpuC)}°C · {value(device.powerDrawW)}/{value(device.powerLimitW)}W</span><MetricBar value={device.utilizationGpuPercent ?? 0} label={`${device.name} utilization`} /></div>{/each}</div></Panel><Panel title="llama processes"><div class="rows">{#each processes?.processes ?? [] as process}<div><b>{managed(process.pid)}</b><span>PID {process.pid} · {process.name} · {process.kind} · {process.confidence}</span><small>Started {process.startedAt ?? "—"} · {process.reasons.join("; ")}</small></div>{:else}<p>No llama processes detected.</p>{/each}</div></Panel><Panel title="GPU processes"><div class="rows">{#each gpu?.processes ?? [] as process}<div><b>{process.kind}</b><span>PID {process.pid} · {process.processName} · {value(process.usedMemoryMiB)} MiB</span><small>{process.reasons.join("; ")}</small></div>{:else}<p>No GPU processes detected.</p>{/each}</div></Panel></div></main>
<style>.actions{display:flex;gap:.6rem;align-items:center;flex-wrap:wrap;margin-bottom:1rem}.actions span{color:var(--color-muted);font-size:.8rem}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1rem}.body,.rows{display:grid;gap:.75rem;padding:1rem}.body p{margin:0}.device,.rows>div{display:grid;gap:.25rem;padding:.55rem 0;border-top:1px solid var(--color-line)}.device span,.rows span,.rows small{color:var(--color-muted);font-size:.8rem}@media(max-width:600px){.grid{grid-template-columns:1fr}}</style>
