import { createHash } from "node:crypto";
import { mkdir, readFile, rename, stat, unlink, writeFile } from "node:fs/promises";
import path from "node:path";
import { isBuildEligibleForManagedInference, isRouterAlias, type CommandSpec, type ConfiguredModel, type GeneratedRouterArtifact, type LlamaBuildCapabilitiesManifest, type LlamaCppArgs, type RouterLaunchPreview, type RouterPresetPreview } from "@obsidianlm/shared";
import { loadPhase15Domain, mutatePhase15Domain, reconcileBuildFingerprintInSnapshot, type Phase15DomainSnapshot } from "../config/phase15-domain.js";
import { getDataDir } from "../config/paths.js";
import { loadSettingsReadOnly } from "../config/storage.js";
import { getLlamaBuildCapabilitiesForServer } from "../discovery/llama-build-capabilities.js";
import { routerAutoloadArgument } from "./autoload-policy.js";
import { fingerprintServerExecutable } from "./fingerprint.js";

const VERSION = "llama-router-preset-v1", MAX_PRESET_BYTES = 1024 * 1024;
const locks = new Set<string>();
const sha = (input: string | Buffer) => createHash("sha256").update(input).digest("hex");
const stable = (value: unknown): string => JSON.stringify(value, (_key, item) => item && typeof item === "object" && !Array.isArray(item) ? Object.fromEntries(Object.entries(item).sort(([a], [b]) => a.localeCompare(b))) : item);
const absolute = (value: string) => path.isAbsolute(value) || path.win32.isAbsolute(value);
const ini = (value: string, field: string): string => { if (!value || /[\0\r\n]/u.test(value) || value.trim() !== value || /(?:^|\s)[;#]/u.test(value)) throw new RouterPresetError("invalid_payload", `${field} is unsafe for an INI preset.`); return value; };
const display = (value: string) => /[\s"]/u.test(value) ? `"${value.replaceAll('"', '\\"')}"` : value;

export class RouterPresetError extends Error { constructor(public readonly code: "not_found" | "prerequisite" | "conflict" | "invalid_payload", message: string) { super(message); } }
export interface RouterPresetDependencies {
  load?: () => Promise<Phase15DomainSnapshot>;
  mutate?: <T>(mutator: (snapshot: Phase15DomainSnapshot) => T | Promise<T>) => Promise<{ snapshot: Phase15DomainSnapshot; result: T }>;
  dataDir?: () => string; fingerprint?: (locator: string) => Promise<string>;
  capabilities?: (server: string, buildId: string, tools: Phase15DomainSnapshot["builds"][number]["tools"]) => Promise<LlamaBuildCapabilitiesManifest>;
  readFile?: (file: string) => Promise<Buffer>; stat?: (file: string) => Promise<{ size: number; mtime: Date }>;
  writeFile?: (file: string, content: string, options?: { flag?: string }) => Promise<void>; mkdir?: (dir: string, options: { recursive: true }) => Promise<unknown>; rename?: (from: string, to: string) => Promise<void>; unlink?: (file: string) => Promise<void>;
  settings?: () => Promise<{ managedLlamaPort: number }>; random?: () => string; now?: () => Date;
}
export interface RouterPresetAnalysis { preview: RouterPresetPreview; capabilityFingerprint: string; sourceHash: string; manifest: LlamaBuildCapabilitiesManifest; executable: string; executableFingerprint: string; }
type Flag = LlamaBuildCapabilitiesManifest["flags"][number];

function flags(manifest: LlamaBuildCapabilitiesManifest): Map<string, Flag> { return new Map(manifest.flags.flatMap((flag) => [flag.canonicalName, ...flag.aliases].map((name) => [name, flag] as const))); }
function capabilityFingerprint(manifest: LlamaBuildCapabilitiesManifest): string {
  return sha(stable(manifest.flags.map((flag) => ({ canonicalName: flag.canonicalName, aliases: [...flag.aliases].sort(), ...(flag.valuePlaceholder ? { valuePlaceholder: flag.valuePlaceholder } : {}), ...(flag.choices?.length ? { choices: [...flag.choices].sort() } : {}), ...(flag.deprecated ? { deprecated: true } : {}), ...(flag.defaultText ? { defaultText: flag.defaultText } : {}), ...(flag.canonicalName === "--no-models-autoload" ? { description: flag.description ?? "" } : {}) })).sort((a, b) => a.canonicalName.localeCompare(b.canonicalName))));
}
function resolved(map: Map<string, Flag>, candidates: string[], model: ConfiguredModel, setting: string): { flag: Flag; key: string } {
  const flag = candidates.map((candidate) => map.get(candidate)).find((item): item is Flag => !!item);
  if (!flag) throw new RouterPresetError("prerequisite", `Model ${model.id} setting ${setting} is not supported by Build ${model.buildId}.`);
  const long = flag.canonicalName.startsWith("--") ? flag.canonicalName : flag.aliases.find((alias) => alias.startsWith("--"));
  if (!long) throw new RouterPresetError("prerequisite", `Model ${model.id} setting ${setting} has no safe long Build option.`);
  const key = long.slice(2); if (!/^[a-z0-9][a-z0-9-]*$/iu.test(key)) throw new RouterPresetError("prerequisite", `Model ${model.id} setting ${setting} resolved to an unsafe Build option.`);
  return { flag, key };
}
const ROUTER_OWNED_OPTIONS = new Set(["-m", "--model", "--alias", "--host", "--port", "--models-preset", "--models-dir", "--models-max", "--models-autoload", "--no-models-autoload", "--mmproj", "--mmproj-file", "--api-key", "--api-key-file"]);
function unsafe(flag: Flag, raw: string): boolean {
  const names = [raw, flag.canonicalName, ...flag.aliases];
  return names.some((name) => ROUTER_OWNED_OPTIONS.has(name.toLowerCase()))
    || /(?:token|secret|api[_-]?key|password|credential|private[_-]?key)/iu.test(`${names.join(" ")} ${flag.environmentAlias ?? ""} ${flag.description ?? ""}`);
}
function value(value: unknown, model: ConfiguredModel, setting: string): string { if (typeof value === "number" && !Number.isFinite(value)) throw new RouterPresetError("invalid_payload", `Model ${model.id} setting ${setting} must be finite.`); if (typeof value === "string" && !value) throw new RouterPresetError("invalid_payload", `Model ${model.id} setting ${setting} must not be empty.`); return ini(String(value), `Model ${model.id} setting ${setting}`); }
function choice(flag: Flag, rendered: string, model: ConfiguredModel, setting: string): void { if (flag.choices?.length && !flag.choices.includes(rendered)) throw new RouterPresetError("invalid_payload", `Model ${model.id} setting ${setting} is not a supported Build choice.`); }
function options(model: ConfiguredModel, manifest: LlamaBuildCapabilitiesManifest): Array<[string, string]> {
  const map = flags(manifest), emitted = new Set<string>(), out: Array<[string, string]> = [];
  const put = (setting: string, candidates: string[], raw: unknown, noValue = false): void => { if (raw === undefined || raw === false) return; const option = resolved(map, candidates, model, setting); if (unsafe(option.flag, option.flag.canonicalName) || emitted.has(option.key)) throw new RouterPresetError("invalid_payload", `Configured Model '${model.displayName}' setting ${setting} duplicates or owns a router option.`); const rendered = noValue ? "true" : value(raw, model, setting); if (!noValue) choice(option.flag, rendered, model, setting); emitted.add(option.key); out.push([option.key, rendered]); };
  const args: LlamaCppArgs = model.llamaArgs ?? {};
  put("ctxSize", ["--ctx-size", "-c"], args.ctxSize);
  if (args.gpuLayers === "all") { const gpu = resolved(map, ["--n-gpu-layers", "--gpu-layers", "-ngl"], model, "gpuLayers"); if (!/(?:^|[^a-z])all(?:[^a-z]|$)/iu.test(`${gpu.flag.valuePlaceholder ?? ""} ${gpu.flag.description ?? ""} ${(gpu.flag.choices ?? []).join(" ")}`)) throw new RouterPresetError("invalid_payload", `Configured Model '${model.displayName}' requires gpuLayers=all, but Build ${model.buildId} does not prove that value.`); }
  put("gpuLayers", ["--n-gpu-layers", "--gpu-layers", "-ngl"], args.gpuLayers === "all" ? "all" : args.gpuLayers);
  if (args.devices?.length) {
    const device = resolved(map, ["--device", "-dev"], model, "devices");
    if (args.devices.length > 1 && !/(?:comma|list|,|\.\.\.)/iu.test(`${device.flag.valuePlaceholder ?? ""} ${device.flag.description ?? ""}`)) throw new RouterPresetError("invalid_payload", `Configured Model '${model.displayName}' has multiple devices, but Build ${model.buildId} does not prove a single-value device-list encoding.`);
    put("devices", ["--device", "-dev"], args.devices.map((item) => value(item, model, "devices")).join(","));
  }
  put("splitMode", ["--split-mode"], args.splitMode); put("tensorSplit", ["--tensor-split"], args.tensorSplit); put("cacheTypeK", ["--cache-type-k"], args.cacheTypeK); put("cacheTypeV", ["--cache-type-v"], args.cacheTypeV); put("flashAttention", ["--flash-attn"], args.flashAttention && "on");
  put("batchSize", ["--batch-size"], args.batchSize); put("ubatchSize", ["--ubatch-size"], args.ubatchSize); put("parallel", ["--parallel"], args.parallel); put("threads", ["--threads", "-t"], args.threads); put("threadsBatch", ["--threads-batch"], args.threadsBatch); put("contBatching", ["--cont-batching"], args.contBatching, true);
  for (const override of [...(model.flagOverrides ?? [])].sort((a, b) => a.flag.localeCompare(b.flag) || (a.values ?? []).join("\0").localeCompare((b.values ?? []).join("\0")))) {
    const flag = map.get(ini(override.flag, "override flag")); if (!flag || unsafe(flag, override.flag)) throw new RouterPresetError("invalid_payload", `Configured Model '${model.displayName}' has an unsafe or unsupported override '${override.flag}'.`); const key = (flag.canonicalName.startsWith("--") ? flag.canonicalName : flag.aliases.find((item) => item.startsWith("--")) ?? "").slice(2); if (!key || emitted.has(key) || (override.values?.length ?? 0) > 1 || !!flag.valuePlaceholder !== !!override.values?.length) throw new RouterPresetError("invalid_payload", `Configured Model '${model.displayName}' has an invalid duplicate or override shape for '${override.flag}'.`); const rendered = override.values?.length ? value(override.values[0], model, "override") : "true"; choice(flag, rendered, model, "override"); emitted.add(key); out.push([key, rendered]);
  }
  for (let index = 0; index < (model.extraArgs?.length ?? 0);) { const raw = model.extraArgs![index++]!; const flag = map.get(raw); if (!flag || unsafe(flag, raw)) throw new RouterPresetError("invalid_payload", `Configured Model '${model.displayName}' has an unsafe or unknown raw argument '${raw}'.`); const key = (flag.canonicalName.startsWith("--") ? flag.canonicalName : flag.aliases.find((item) => item.startsWith("--")) ?? "").slice(2); const next = model.extraArgs![index]; if (!key || emitted.has(key) || (flag.valuePlaceholder && (!next || next.startsWith("-"))) || (!flag.valuePlaceholder && next && !next.startsWith("-"))) throw new RouterPresetError("invalid_payload", `Raw argument '${raw}' cannot be safely represented in a llama.cpp model preset for this Build.`); const rendered = flag.valuePlaceholder ? value(model.extraArgs![index++]!, model, "extra argument") : "true"; choice(flag, rendered, model, "extra argument"); emitted.add(key); out.push([key, rendered]); }
  return out;
}
async function invalidate(buildId: string, fingerprint: string | undefined, dependencies: RouterPresetDependencies, message: string): Promise<void> { await (dependencies.mutate ?? mutatePhase15Domain)((snapshot) => reconcileBuildFingerprintInSnapshot(snapshot, buildId, fingerprint, message)); }
export async function analyzeRouterPreset(buildId: string, dependencies: RouterPresetDependencies = {}): Promise<RouterPresetAnalysis> {
  const snapshot = await (dependencies.load ?? loadPhase15Domain)(), build = snapshot.builds.find((entry) => entry.id === buildId); if (!build) throw new RouterPresetError("not_found", "Build not found."); if (build.server.owner.scope !== "local") throw new RouterPresetError("conflict", "Router presets cannot be generated for a Node-owned Build.");
  const fingerprint = dependencies.fingerprint ?? fingerprintServerExecutable; let pre: string; try { pre = await fingerprint(build.server.locator); } catch { await invalidate(buildId, undefined, dependencies, "Router preset generation was invalidated because the registered server executable is missing."); throw new RouterPresetError("prerequisite", "The registered llama-server executable is unavailable."); }
  if (!isBuildEligibleForManagedInference(build) || build.serverFingerprint !== pre || build.functionalEvidence?.serverFingerprint !== pre) { await invalidate(buildId, pre, dependencies, "Router preset generation was invalidated because Build validation is stale."); throw new RouterPresetError("prerequisite", "Build is not currently validated for managed inference."); }
  const manifest = await (dependencies.capabilities ?? getLlamaBuildCapabilitiesForServer)(build.server.locator, build.id, build.tools); const post = await fingerprint(build.server.locator).catch(() => undefined); if (post !== pre) { await invalidate(buildId, post, dependencies, "Router preset generation was invalidated because the server executable changed during capability inspection."); throw new RouterPresetError("conflict", "Build executable changed during capability inspection."); }
  try { routerAutoloadArgument(manifest); } catch { throw new RouterPresetError("prerequisite", "Build help does not prove that router model autoload is enabled."); } const models = snapshot.configuredModels.filter((model) => model.buildId === build.id && model.enabled).sort((a, b) => a.routerAlias.localeCompare(b.routerAlias) || a.id.localeCompare(b.id)); if (!models.length) throw new RouterPresetError("prerequisite", "At least one enabled model is required for a router preset.");
  const map = flags(manifest); const sections = models.map((model) => { if (!isRouterAlias(model.routerAlias)) throw new RouterPresetError("invalid_payload", `Configured Model '${model.displayName}' has an unsafe router alias.`); const artifact = snapshot.artifacts.find((item) => item.id === model.artifactId); if (!artifact || !["model", "unknown"].includes(artifact.kind) || artifact.referenceStatus !== "available" || artifact.resource.owner.scope !== "local" || !absolute(artifact.resource.locator)) throw new RouterPresetError("prerequisite", `Model ${model.id} is not a local available absolute model artifact.`); const projector = model.projector ? snapshot.artifacts.find((item) => item.id === model.projector!.artifactId) : undefined; if (model.projector && (!projector || !["mmproj", "unknown"].includes(projector.kind) || projector.referenceStatus !== "available" || projector.resource.owner.scope !== "local" || !absolute(projector.resource.locator))) throw new RouterPresetError("prerequisite", `Projector for model ${model.id} is not a local available absolute mmproj artifact.`); const projectorKey = projector ? resolved(map, ["--mmproj", "--mmproj-file"], model, "projector").key : undefined; return { model, artifact, projector, projectorKey, options: options(model, manifest) }; });
  const content = `version = 1\n\n${sections.map(({ model, artifact, projector, projectorKey, options }) => `[${ini(model.routerAlias, "router alias")}]\nmodel = ${ini(artifact.resource.locator, "model path")}\n${projector ? `${projectorKey} = ${ini(projector.resource.locator, "projector path")}\n` : ""}${options.map(([key, item]) => `${key} = ${item}\n`).join("")}\n`).join("")}`;
  const cap = capabilityFingerprint(manifest), sourceHash = sha(stable({ generatorVersion: VERSION, buildId, validatedFingerprint: pre, capabilityFingerprint: cap, models: sections.map(({ model, artifact, projector }) => ({ id: model.id, alias: model.routerAlias, llamaArgs: model.llamaArgs, flagOverrides: model.flagOverrides, extraArgs: model.extraArgs, artifact: { id: artifact.id, owner: artifact.resource.owner, locator: artifact.resource.locator, status: artifact.referenceStatus, kind: artifact.kind }, projector: projector && { id: projector.id, owner: projector.resource.owner, locator: projector.resource.locator, status: projector.referenceStatus, kind: projector.kind } })) })); const locator = path.join(dependencies.dataDir?.() ?? getDataDir(), "generated", "llama-router", `${build.id}.ini`); const reader = dependencies.readFile ?? readFile, info = await (dependencies.stat ?? stat)(locator).catch(() => undefined), existing = info && info.size <= MAX_PRESET_BYTES ? await reader(locator).catch(() => undefined) : undefined;
  const freshness = !info ? "unknown" : info.size > MAX_PRESET_BYTES || !existing || !Buffer.from(content).equals(existing) ? "stale" : "current"; const artifact: GeneratedRouterArtifact = { schemaVersion: 1, authority: "derived", buildId: build.id, resource: { owner: { scope: "local" }, locator }, generatorVersion: VERSION, sourceRevision: sourceHash, contentHash: sha(content), ...(freshness === "current" && info ? { generatedAt: info.mtime.toISOString() } : {}), freshness, validationState: "valid", warnings: [...(models.some((model) => model.llamaArgs?.metrics) ? ["metrics is server-wide and is not emitted in model presets."] : []), ...(models.some((model) => model.llamaArgs?.webui) ? ["webui is server-wide and is not emitted in model presets."] : [])], errors: [] };
  return { preview: { kind: "model_preset", buildId: build.id, artifact, content, configuredModelIds: models.map((model) => model.id) }, capabilityFingerprint: cap, sourceHash, manifest, executable: build.server.locator, executableFingerprint: pre };
}
export async function generateRouterPreset(buildId: string, dependencies: RouterPresetDependencies = {}): Promise<RouterPresetPreview> { if (locks.has(buildId)) throw new RouterPresetError("conflict", "Router preset generation is already running for this Build."); locks.add(buildId); const remove = dependencies.unlink ?? unlink; try { const initial = await analyzeRouterPreset(buildId, dependencies), target = initial.preview.artifact.resource.locator, temp = `${target}.${dependencies.random?.() ?? `${process.pid}.${Date.now()}.${Math.random()}`}.tmp`; await (dependencies.mkdir ?? mkdir)(path.dirname(target), { recursive: true }); try { await (dependencies.writeFile ?? writeFile)(temp, initial.preview.content, { flag: "wx" }); const bytes = await (dependencies.readFile ?? readFile)(temp); if (bytes.length !== Buffer.byteLength(initial.preview.content) || sha(bytes) !== initial.preview.artifact.contentHash) throw new RouterPresetError("conflict", "Temporary router preset bytes did not verify."); const current = await analyzeRouterPreset(buildId, dependencies); if (current.sourceHash !== initial.sourceHash || current.executable !== initial.executable || current.executableFingerprint !== initial.executableFingerprint || current.preview.content !== initial.preview.content) throw new RouterPresetError("conflict", "Router preset source changed during generation."); await (dependencies.rename ?? rename)(temp, target); return { ...initial.preview, artifact: { ...initial.preview.artifact, generatedAt: (dependencies.now ?? (() => new Date()))().toISOString(), freshness: "current" } }; } finally { await remove(temp).catch(() => undefined); } } finally { locks.delete(buildId); } }
export async function buildRouterLaunchPreview(buildId: string, dependencies: RouterPresetDependencies = {}): Promise<RouterLaunchPreview> { const analysis = await analyzeRouterPreset(buildId, dependencies), map = flags(analysis.manifest), launch = { id: "launch", displayName: "managed router", buildId } as unknown as ConfiguredModel, modelPreset = resolved(map, ["--models-preset"], launch, "models preset"), modelsMax = resolved(map, ["--models-max"], launch, "models max"), host = resolved(map, ["--host"], launch, "host"), port = resolved(map, ["--port"], launch, "port"), autoload = routerAutoloadArgument(analysis.manifest), settings = await (dependencies.settings ?? loadSettingsReadOnly)(); const args = [`--${host.key}`, "0.0.0.0", `--${port.key}`, String(settings.managedLlamaPort), `--${modelPreset.key}`, analysis.preview.artifact.resource.locator, `--${modelsMax.key}`, "1", ...(autoload ? [autoload] : [])]; const command: CommandSpec = { executable: analysis.executable, args, displayCommand: [analysis.executable, ...args].map(display).join(" "), commandHash: sha(stable({ executable: analysis.executable, args })) }; return { kind: "router_launch", command, artifact: analysis.preview.artifact, policy: { modelsMax: 1, modelsAutoload: true } }; }
